name: LZBR
description: $description
version: '${version}'

main: com.github.Glatinis.lZBR.core.LZBR
api-version: '26.1.2'
load: POSTWORLD
softdepend: [Multiverse-Core, FastAsyncWorldEdit]

commands:
  lzbr:
    usage: /<command> <join | start | leave | end | arena | loot | mobs | test>
    alias: [lz]

authors: [ Glatinis ]
